# Generated by Django 5.0.1 on 2024-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['user'], 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='order',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
